### ISSUE TITLE
решить как реализовать это все для extra книги

### ISSUE THREAD

**Issue by makpif** [Linux4Yourself/Linux4Yourself.HomePage#5]

**Comment by avmaisak** [comment]
есть репозиторий Extra. перенесём в него "каркас" с основной. И можно настроить деплой по адресу  - lx4u.ru/dev/extra/

**Comment by avmaisak** [comment]
+ файл для пакетов создать

**Comment by makpif** [comment]
это то я понимаю, имею ввиду как на сайте оформить?
сделать кнопку которая кидает на аналогичную страницу (как в лфс) или рядом stable dev extra-stable extra-dev ?

**Comment by avmaisak** [comment]
рядом наверное
